/**
 * Every retired WordPress URL and what happens to it. Source of truth for next.config.ts redirects
 * and rewrites, and for scripts/verify-routes.ts. Each redirect is a single hop.
 */

/** Old URL -> new URL, served as 301. */
export const permanentRedirects: { source: string; destination: string }[] = [
  {
    source: "/the-role-and-importance-of-brand-strategy-consulting-in-business-success/",
    destination: "/",
  },
  { source: "/building-a-powerful-brand-strategy/", destination: "/writing/" },
  {
    source: "/brand-strategy-consulting-unlocking-success-through-strategic-partnerships/",
    destination: "/",
  },
  {
    source: "/settling-for-good-enough-startup-branding-is-limiting-your-growth/",
    destination: "/",
  },
  {
    source: "/enhancing-your-business-with-brand-marketing-strategy-consulting/",
    destination: "/",
  },
  {
    source: "/mastering-b2b-brand-strategy-10-key-steps-for-building-a-strong-brand/",
    destination: "/writing/",
  },
  {
    source: "/unlocking-the-power-of-brand-strategy-a-guide-to-choosing-a-top-branding-agency/",
    destination: "/",
  },
  { source: "/choosing-the-right-brand-agency-for-you/", destination: "/" },
  { source: "/unveiling-the-power-of-personal-branding/", destination: "/writing/" },
  { source: "/comprehensive-guide-to-successful-brand-building/", destination: "/" },
  {
    source: "/the-art-and-science-of-brand-identity-building-a-lasting-impression/",
    destination: "/",
  },
  { source: "/brand-messaging-guide-from-strategy-to-implementation/", destination: "/writing/" },
  { source: "/10-signs-your-brand-strategy-needs-a-refresh/", destination: "/writing/" },
  { source: "/5-common-brand-identity-problems-and-their-solutions/", destination: "/" },
  {
    source: "/brand-positioning-vs-brand-identity-key-differences-explained/",
    destination: "/writing/",
  },
  { source: "/brand-positioning-frequently-asked-questions/", destination: "/writing/" },
  {
    source: "/how-to-create-an-authentic-brand-voice-step-by-step-guide/",
    destination: "/writing/",
  },
  { source: "/b2b-vs-b2c-brand-strategy-a-comparative-analysis/", destination: "/writing/" },
  {
    source: "/brand-voice-checklist-12-elements-of-compelling-messaging/",
    destination: "/writing/",
  },
  { source: "/5-steps-to-tailor-value-propositions-for-audiences/", destination: "/writing/" },
  { source: "/how-to-measure-brand-consistency/", destination: "/writing/" },
  { source: "/why-consistency-in-brand-voice-drives-growth/", destination: "/writing/" },
  { source: "/7-editing-tips-for-clearer-brand-messaging/", destination: "/writing/" },
  { source: "/how-to-adjust-brand-voice-for-new-audiences/", destination: "/writing/" },
  { source: "/how-to-measure-value-proposition-roi/", destination: "/writing/" },
  { source: "/how-to-improve-customer-perception/", destination: "/" },
  { source: "/ultimate-guide-to-multi-channel-brand-messaging/", destination: "/writing/" },
  { source: "/how-brand-tone-impacts-customer-perception/", destination: "/writing/" },
  { source: "/how-to-build-omnichannel-brand-consistency/", destination: "/writing/" },
  { source: "/how-to-write-a-brand-story-that-resonates/", destination: "/writing/" },
  { source: "/5-visual-storytelling-tips-for-startup-copy/", destination: "/writing/" },
  { source: "/how-to-craft-stories-that-resonate-with-customers/", destination: "/writing/" },
  { source: "/key-components-of-brand-positioning-strategy/", destination: "/writing/" },
  { source: "/why-personas-matter-in-rebranding-strategies/", destination: "/" },
  { source: "/how-emotions-shape-buying-behavior/", destination: "/why-some-brands-move-us/" },
  { source: "/steps-to-write-a-brand-positioning-statement/", destination: "/writing/" },
  { source: "/10-slides-for-a-winning-pitch-deck/", destination: "/writing/" },
  {
    source: "/why-emotional-resonance-matters-in-brand-messaging/",
    destination: "/why-some-brands-move-us/",
  },
  { source: "/how-to-build-trust-through-brand-messaging/", destination: "/writing/" },
  { source: "/how-to-balance-humor-and-emotion-in-brand-stories/", destination: "/writing/" },
  { source: "/how-everyday-stories-strengthen-brand-messaging/", destination: "/writing/" },
  { source: "/how-to-create-scalable-messaging-for-growing-brands/", destination: "/writing/" },
  { source: "/how-ai-improves-cross-channel-messaging-at-scale/", destination: "/writing/" },
  { source: "/5-steps-to-define-brand-purpose/", destination: "/" },
  {
    source: "/how-to-measure-emotional-impact-in-branding/",
    destination: "/why-some-brands-move-us/",
  },
  { source: "/how-to-measure-brand-storytelling-roi/", destination: "/writing/" },
  { source: "/how-to-phase-a-legacy-brand-refresh/", destination: "/" },
  { source: "/how-storytelling-enhances-customer-journey-copy/", destination: "/writing/" },
  { source: "/how-to-ensure-messaging-consistency-across-channels/", destination: "/writing/" },
  { source: "/build-strategic-brand-story-stands-out/", destination: "/writing/" },
  { source: "/scale-brand-authentic-storytelling/", destination: "/writing/" },
  { source: "/improve-pitch-deck-investor-meetings/", destination: "/writing/" },
  { source: "/signature-story-persuasive-guide/", destination: "/writing/" },
  { source: "/20-second-quiz/", destination: "/" },
  { source: "/pitchcraft-hidden-testing/", destination: "/pitchcraft/" },
  { source: "/ready-to-move/", destination: "/contact/" },
  { source: "/resultsmovere/", destination: "/work/" },
  { source: "/skills/", destination: "/about/" },
  { source: "/catalyst/", destination: "/about/" },
  { source: "/on-brand/", destination: "/work/" },
  {
    source: "/the-power-of-branding-agencies-unlocking-your-businesss-potential/",
    destination: "/",
  },
  { source: "/process/", destination: "/about/#method" },
  { source: "/b2b-brand-strategy/", destination: "/" },
  { source: "/experience/", destination: "/about/" },
  { source: "/privacy-policy/", destination: "/privacy-policy-2/" },
  { source: "/shop/", destination: "/" },
  { source: "/my-account/", destination: "/" },
  { source: "/checkout/", destination: "/" },
  { source: "/cart/", destination: "/" },
  { source: "/portfolio/", destination: "/work/" },
  {
    source: "/portfolio/driving-membership-for-disney-vacation-club/",
    destination: "/work/#disney",
  },
  {
    source: "/portfolio/helping-ea-maddens-creative-agency-score-more-points/",
    destination: "/work/",
  },
  {
    source: "/portfolio/nickelodeon-upping-the-fun-and-engagement-20-yoy-increase/",
    destination: "/work/nickelodeon-kids-choice-awards/",
  },
  {
    source: "/portfolio/google-search-result-creative-impact-cannes-cyber-lion-winner/",
    destination: "/work/google-project-rebrief/",
  },
  {
    source: "/portfolio/american-red-cross-pumping-up-blood-donations-by-30/",
    destination: "/work/#american-red-cross",
  },
  {
    source: "/portfolio/microsoft-programmed-for-growth-18-increase-in-online-conversions/",
    destination: "/work/microsoft/",
  },
  {
    source: "/portfolio/hard-rock-cafe-international-drumming-up-in-store-traffic-15-increase/",
    destination: "/work/hard-rock-cafe/",
  },
  {
    source:
      "/portfolio/apto-solutions-creating-foundational-assets-for-an-it-asset-disposition-company-2/",
    destination: "/work/apto-solutions/",
  },
  {
    source: "/portfolio/shining-a-spotlight-on-the-new-broadway-com-experience/",
    destination: "/work/",
  },
  {
    source: "/portfolio/sony-connected-world-connecting-the-dots-for-a-seamless-experience/",
    destination: "/work/sony-connected-world/",
  },
  {
    source: "/portfolio/intel-core-m-powering-the-launch-of-the-latest-chip/",
    destination: "/work/intel/",
  },
  {
    source: "/portfolio/intel-action-oriented-messaging-for-a-social-action-campaign/",
    destination: "/work/intel/",
  },
  {
    source: "/portfolio/retelling-the-story-of-the-google-ramayana-project/",
    destination: "/work/",
  },
  {
    source: "/portfolio/highlighting-the-creative-reinvention-of-the-wacom-site/",
    destination: "/work/",
  },
  { source: "/portfolio/the-story-behind-a-full-relaunch-of-usa-today/", destination: "/work/" },
  {
    source: "/portfolio/remark-growth-marketing-driving-conversions-for-a-marketing-agency/",
    destination: "/work/remark-growth-marketing/",
  },
  {
    source: "/portfolio/gis-giving-life-to-a-life-coaching-brand-from-scratch/",
    destination: "/work/",
  },
  {
    source: "/portfolio/the-future-of-airline-websites-site-of-the-day-award/",
    destination: "/work/",
  },
  {
    source: "/portfolio/tria-beauty-brand-makeover-66-yoy-growth-in-website-revenue/",
    destination: "/work/tria-beauty/",
  },
  { source: "/portfolio/sf-innovation-hub/", destination: "/pitchcraft/" },
  {
    source: "/portfolio/intel-chipping-in-to-boost-conversions-25-jump-in-sales/",
    destination: "/work/intel/",
  },
  { source: "/portfolio/google-insynch/", destination: "/pitchcraft/" },
  { source: "/portfolio/lax/", destination: "/pitchcraft/" },
  { source: "/portfolio/premera-blue-cross/", destination: "/pitchcraft/" },
  {
    source: "/portfolio/ledger-leading-the-future-of-crypto-and-web3/",
    destination: "/work/ledger/",
  },
];

/** Retired URLs, served as 410 Gone by app/gone/route.ts. */
export const gonePaths: string[] = [
  "/top-branding-agencies-defining-the-future-of-branding/",
  "/top-branding-agencies-elevating-your-brand-strategy-with-expert-consulting/",
  "/luxury-real-estate-personal-branding-guide/",
  "/top-brand-strategy-tools-for-startups-in-2025/",
  "/persona-development-frameworks-for-startups/",
  "/how-accessibility-impacts-brand-perception/",
  "/how-language-impacts-brand-name-success/",
  "/10-video-seo-tips-for-brand-visibility/",
  "/how-real-time-polling-tools-improve-audience-engagement/",
  "/7-post-event-follow-up-tactics-for-virtual-events/",
  "/swot-analysis-for-brand-strategy-basics/",
  "/how-chatbots-improve-customer-engagement-across-channels/",
  "/how-conversational-ai-builds-brand-trust/",
  "/brand-purpose-evolution-key-shifts-over-decades/",
  "/how-mobile-data-tools-improve-audience-research/",
  "/7-win-back-campaign-strategies-for-customer-retention/",
  "/ultimate-guide-to-user-centered-content-strategy/",
  "/case-studies-success-with-community-centric-brands/",
  "/brand-compliance-vs-brand-governance/",
  "/van-westendorp-method-steps-to-measure-price-sensitivity/",
  "/how-to-create-brand-guidelines-in-5-steps/",
  "/top-5-challenges-in-measuring-brand-equity/",
  "/e-a-t-principles-for-seo-content-accuracy/",
  "/trademark-clearance-search-steps-for-business-names/",
  "/how-to-choose-fonts-for-multilingual-brands/",
  "/how-to-measure-emotional-impact-of-sensory-branding/",
  "/how-predictive-analytics-shapes-brand-strategy/",
  "/ultimate-guide-to-customer-lifetime-value/",
  "/product-interaction-segmentation-step-by-step-guide/",
  "/how-brands-measure-sentiment-in-crisis-management/",
  "/cross-channel-personalization-best-segmentation-practices/",
  "/how-to-build-brand-narratives-for-metaverse-audiences/",
  "/ethical-issues-in-focus-groups/",
  "/what-is-occasion-based-segmentation/",
  "/behavioral-segmentation-for-price-sensitive-audiences/",
  "/how-broken-links-hurt-brand-visibility/",
  "/digital-tech-in-pop-ups-case-studies/",
  "/how-focus-groups-drive-brand-strategy/",
  "/tactile-branding-7-strategies-for-memorable-interactions/",
  "/dynamic-content-personalization-best-practices/",
  "/integrating-paid-owned-earned-media-5-steps/",
  "/how-co-creation-builds-brand-loyalty/",
  "/5-metrics-for-measuring-event-brand-awareness/",
  "/content-formatting-rules-for-brand-guidelines/",
  "/how-to-prioritize-usability-issues-in-testing/",
  "/avoiding-legal-issues-in-content-marketing/",
  "/how-sentiment-analysis-shapes-crisis-responses/",
  "/ultimate-guide-to-cross-channel-message-timing/",
  "/ultimate-guide-to-ai-content-repurposing/",
  "/how-brand-consolidation-impacts-customer-perception/",
  "/early-crisis-detection-with-social-media-sentiment/",
  "/how-to-evaluate-competitors-in-new-markets/",
  "/common-persona-validation-mistakes-to-avoid/",
  "/5-steps-to-build-personas-for-better-marketing/",
  "/cross-platform-content-versioning-vs-traditional-workflows/",
  "/retention-curve-analysis-for-startups/",
  "/loyalty-based-segmentation-for-small-businesses/",
  "/how-multi-language-surveys-improve-audience-research/",
  "/sentiment-analysis-vs-brand-perception-analysis/",
  "/10-examples-of-strong-brand-mission-statements/",
  "/maximizing-roi-with-content-repurposing/",
  "/solving-brand-disconnect-with-sensory-packaging/",
  "/how-to-create-stylescape-for-brand-identity/",
  "/xml-sitemap-integration-benefits-for-brand-websites/",
  "/brand-name-generator-unique-ideas/",
  "/test-form/",
  "/elementor-hf/6610/",
  "/elementor-hf/6674/",
  "/elementor-hf/6679/",
  "/wp-content/uploads/2016/03/CR-Resume_ACD_2016.pdf",
];

/** Old URLs that still exist at the same path and must return 200. */
export const keptPaths: string[] = [
  "/why-some-brands-move-us/",
  "/unlocking-utopia-the-innocent-archetype-in-branding-2/",
  "/embracing-the-maverick-rebel-archetypes-clout-in-branding/",
  "/7-brand-strategy-frameworks-that-drive-business-growth/",
  "/5-successful-brand-repositioning-case-studies/",
  "/",
  "/pitchcraft/",
  "/privacy-policy-2/",
  "/terms-conditions/",
  "/shipping-refund-policy/",
  "/work/wacom/",
];
